# Generated by Django 3.2.4 on 2021-06-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(default='null', upload_to='storage/image'),
            preserve_default=False,
        ),
    ]
