# Generated by Django 3.2.4 on 2021-06-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_service_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(blank=True, upload_to='storage/image/%Y/%m/%d/'),
        ),
    ]
