# Generated by Django 3.2.4 on 2021-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210629_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo_fa',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
