# Generated by Django 3.2.4 on 2021-07-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_service_logo_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='storage/image/%Y/%m/%d/'),
        ),
    ]
