# Generated by Django 3.2.4 on 2021-07-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.IntegerField(choices=[(0, 'Game'), (1, 'Website'), (2, 'Design')], default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='work_type',
            field=models.IntegerField(choices=[(0, 'Personal'), (1, 'Commission')], default=0),
        ),
    ]
