# Generated by Django 3.2.4 on 2021-07-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210714_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-create_at']},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='created_on',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='updated_on',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_on',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_on',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='updated_on',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='created_on',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='updated_on',
            new_name='update_at',
        ),
    ]
