# Generated by Django 3.2.4 on 2021-07-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210714_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
