# Generated by Django 3.2.4 on 2021-07-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(default='https://ba-ka.org/', max_length=256),
            preserve_default=False,
        ),
    ]
